v4w_controller:
  port: "/dev/arduinoMega"
  baud: 115200
  scheduler: "fifo"
  priority: 98

joystick:
  deadzone: 0.0
  scheduler: "fifo"
  priority: 98
  autorepeat_rate: 50 
  coalesce_interval: 0.02

camera_stablilizer:
  kp: 0.5
  ki: 0.0
  kd: 0.0
  reset_angle: 0.0
  max_angle: 0.5
  min_angle: -0.1
  rate: 50

v4w_control:
  lock_front_diffs: true
  lock_rear_diffs: true
  low_gear: true
  max_speed: 1.8
  min_speed: -1.8
  max_steering_angle: 0.78
  min_steering_angle: -0.78
  max_acceleration: 0.2
  min_acceleration: -0.2