v4w_controller:
  port: "/dev/teensy"
  baud: 57600
  scheduler: "fifo"
  priority: 98

joystick:
  deadzone: 0.0
  scheduler: "fifo"
  priority: 98
  autorepeat_rate: 50 
  coalesce_interval: 0.02

camera_stabilizer:
  kp: 0.5
  ki: 0.0
  kd: 0.0
  cam_reset_angle: 0.0
  cam_min_angle: -0.0
  cam_max_angle: 1.0
  rate: 50

v4w_control:
  lock_front_diffs: true
  lock_rear_diffs: true
  low_gear: true
  max_vel: 2.1
  min_vel: -0.8
  max_joy_vel: 1.0
  min_joy_vel: -1.0
  max_steering_angle: 0.78
  min_steering_angle: -0.78
  max_acceleration: 5.0
  min_acceleration: -1.0